var myApp=angular.module('myApp',['ui.router','ngFileUpload']);
myApp.config(function($stateProvider,$urlRouterProvider,$httpProvider){
	$stateProvider
	.state('login',{
		url:'/login',
		templateUrl:'./login.html',
		controller:'login_controller'
	})
	.state('home',{
		url:'/home',
		templateUrl:'./home.html',
		controller:'home_controller'
	})
	.state('register',{
		url:'/register',
		templateUrl:'./register.html',
		controller:'register_controller'
	})
	.state('forgot',{
		url:'/forgotPassword',
		templateUrl:'./forgot.html',
		controller:'forgot_controller'
	})
	.state('reset',{
		url:'/reset_password/:email',
		templateUrl:'./reset_password.html',
		controller:'reset_password_controller'
	})
	.state('services',{
		url:'/services',
		templateUrl:'./services.html',
		controller:'services'
	})
	.state('newPost',{
		url:'/new_post',
		templateUrl:'./new_post.html',
		controller:'new_post_controller'
	})
	.state('myProfile',{
		url:'/my_profile',
		templateUrl:'./my_profile.html',
		controller:'my_profile_controller'
	})
	.state('singlePost',{
		url:'/single_post/:postId',
		templateUrl:'./single_post.html',
		controller:'single_post_controller'
	})
	.state('editProfile',{
		url:'/edit_profile/:postId',
		templateUrl:'./edit_profile.html',
		controller:'edit_profile_controller'
	})
	.state('about',{
		url:'/about',
		templateUrl:'./about.html',
		controller:'about_controller'
	})
	.state('fileUpload',{
		url:'/fileUpload',
		templateUrl:'./file_upload.html',
		controller:'file_upload_controller'
	})
	$urlRouterProvider.otherwise('login');
});